UI/Blueprints/bank/views.py
from flask import Blueprint, json, render_template,request,session,jsonify
from flask.helpers import url_for
import requests	
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

bank = Blueprint('bank', __name__, template_folder="templates")

@bank.route('/bank')
def dashboard():

    _balance={'':''}
    _card={'':''}
    _verified={'':''}
    _session_id=session.get('session')
    if _session_id and session.get('session')!='-1' and session.get('session')!=None:
        headers = {'Content-type': 'application/json', 'Accept': 'text/plain'} #-----------------
        body=json.dumps({"session_id":_session_id})                 # Zahtev za api
        res=requests.post("http://host.docker.internal:5000/api/dashboardData", data=body,headers=headers) #-----
        _json_res = res.json()  
        if _json_res:
            _balance=_json_res['balance']
            _card = _json_res['card']
            _verified=_json_res['verified']

    return render_template("bank_dashboard.html",balance=_balance,card=_card,verified=_verified)

@bank.route('/card')
def card():
    _session_id=session.get('session')
    if _session_id and session.get('session')!='-1' and session.get('session')!=None:
        headers = {'Content-type': 'application/json', 'Accept': 'text/plain'} #-----------------
        body=json.dumps({"session_id":_session_id})                 # Zahtev za api
        res=requests.post("http://host.docker.internal:5000/api/getCurrenciesAddFunds", data=body,headers=headers) #-----
        _json_res = res.json()
        _currenc = _json_res['curr']
    return render_template("card.html",  curr=json.loads(_currenc))

@bank.route('/transactions')
def transactions():
    _session_id=session.get('session')
    _data=[0]
    if _session_id and session.get('session')!='-1' and session.get('session')!=None:
        headers = {'Content-type': 'application/json', 'Accept': 'text/plain'} #-----------------
        body=json.dumps({"session_id":_session_id})                 # Zahtev za api
        res=requests.post("http://host.docker.internal:5000/api/getAllTransactions", data=body,headers=headers) #-----
        _data=json.loads(res.text)
    return render_template("transactions.html", data=_data)

@bank.route('/transfer')
def transfer():
    _session_id=session.get('session')
    if _session_id and session.get('session')!='-1' and session.get('session')!=None:
        headers = {'Content-type': 'application/json', 'Accept': 'text/plain'} #-----------------
        body=json.dumps({"session_id":_session_id})                 # Zahtev za api
        res=requests.post("http://host.docker.internal:5000/api/getOwnCurrencies", data=body,headers=headers) #-----
        _json_res = res.json()
        _currenc = _json_res['curr']
    return render_template("transfer_money.html", curr=json.loads(_currenc))

@bank.route('/exhange')
def exchange():
    _session_id=session.get('session')
    if _session_id and session.get('session')!='-1' and session.get('session')!=None:
        headers = {'Content-type': 'application/json', 'Accept': 'text/plain'} #-----------------
        body=json.dumps({"session_id":_session_id})                 # Zahtev za api
        res=requests.post("http://host.docker.internal:5000/api/getCurrencies", data=body,headers=headers) #-----
        _json_res = res.json()
        _from = _json_res['from']
        _to = _json_res['to']
    return render_template("exchange.html", _from=json.loads(_from),_to=json.loads(_to))

@bank.route('/transferInitiate', methods=['POST'])
def transferInitiate():
    content_ret={'non':'non'}
    _currency = request.form['currency']
    _amount = request.form['amount']
    _transfer_to = request.form['trTo']
    _session_id=session.get('session')
    if _session_id and session.get('session')!='-1' and session.get('session')!=None:
         if _currency and _amount:
            headers = {'Content-type': 'application/json', 'Accept': 'text/plain'} #-----------------
            body=json.dumps({"transfer":_transfer_to,"currency":_currency,"amount":_amount,"session_id":_session_id})                 # Zahtev za api
            res=requests.post("http://host.docker.internal:5000/api/transfer", data=body,headers=headers) #-----
            _json_res=res.json()
            content_ret=_json_res['status']

    return content_ret

@bank.route('/exchangeInitiate',methods=['POST'])
def exhangeInitiate():
    content_ret={'non':'non'}
    _currency_from = request.form['currencyFrom']
    _amount = request.form['amount']
    _currency_to = request.form['currencyTo']
    _session_id=session.get('session')
    if _session_id and session.get('session')!='-1' and session.get('session')!=None:
         if _currency_from and _amount and _currency_to:
            headers = {'Content-type': 'application/json', 'Accept': 'text/plain'} #-----------------
            body=json.dumps({"currencyfrom":_currency_from,"currencyto":_currency_to,"amount":_amount,"session_id":_session_id})                 # Zahtev za api
            res=requests.post("http://host.docker.internal:5000/api/exchange", data=body,headers=headers) #-----
            _json_res=res.json()
            content_ret=_json_res['status']

    return content_ret


@bank.route('/verifyOACC', methods=['POST'])
def addCard():
    _card_number = request.form['cardNum']
    _user_name = request.form['userName']
    _pin_code = request.form['pinCode']
    _expiration_date = request.form['expDate']
    _session_id=session.get('session')
    verified='not verified'
    if _session_id and session.get('session')!='-1' and session.get('session')!=None:
        if _card_number and _user_name and _pin_code and _expiration_date:
            headers = {'Content-type': 'application/json', 'Accept': 'text/plain'} #-----------------
            body=json.dumps({"card_number":_card_number,"user_name":_user_name,"pin_code":_pin_code,
                            "expiration_date":_expiration_date,"session_id":_session_id})                 # Zahtev za api
            res=requests.post("http://host.docker.internal:5000/api/verifyOACC", data=body,headers=headers) #-----
            _json_res=res.json()
            verified=_json_res['card']
            

    return json.dumps(verified)

@bank.route('/addFunds',methods=['POST'])
def addFunds():
    _currency = request.form['currency']
    _amount = request.form['amount']
    _session_id=session.get('session')
    verified='not verified'
    if _session_id and session.get('session')!='-1' and session.get('session')!=None:
         if _currency and _amount:
            headers = {'Content-type': 'application/json', 'Accept': 'text/plain'} #-----------------
            body=json.dumps({"currency":_currency,"amount":_amount,"session_id":_session_id})                 # Zahtev za api
            res=requests.post("http://host.docker.internal:5000/api/addFunds", data=body,headers=headers) #-----
            _json_res=res.json()
            verified=_json_res['card']
    
    return json.dumps(verified)


    #host.docker.internal pre bilo 127.0.0.1 !!!!!!!!!!

UI/Blueprints/bank/templates/bank_dashboard.html
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}"/>
  <meta name="author" content="SitePoint">
</head>

<body>
  <ul style="width: 300px; line-height: 180%;" class="hornav-ul" >
    <li style="background-color: orange; height: 47px; width: 100%; float: left;" class="hornav-li"><img style="display: block; height: 50px; width: 50px; margin-bottom: 10px; margin-left: auto; margin-right: auto;" src="{{url_for('static', filename = 'images/shiba2.png')}}"/></li>
    <li style="width: 100%;" class="hornav-li-text active"><a class="hornav-a"  href="{{ url_for('bank.dashboard') }}">Dashboard</a></li>
    <li style="width: 100%;" class="hornav-li-text"><a class="hornav-a" href="{{ url_for('bank.transactions') }}">Transactions</a></li>
    <li style="width: 100%;" class="hornav-li-text"><a class="hornav-a"  href="{{ url_for('bank.card') }}">Credit card</a></li>
    <li style="width: 100%;" class="hornav-li-text"><a class="hornav-a" href="{{ url_for('bank.transfer') }}">Transfer money</a></li>
    <li style="width: 100%;" class="hornav-li-text"><a class="hornav-a" href="{{ url_for('bank.exchange') }}">Exchange currency</a></li>
  </ul>

  <ul class="topnav-ul">
    <li class="topnav-li"><a class="topnav-a" href="{{ url_for('main.logOut') }}">Log out</a></li>
    <li class="topnav-li"><a class="topnav-a" href="{{ url_for('main.profile') }}">Profile</a></li>
  </ul>
  <div style="position: absolute; top:50px; left: 270px;">
    <table style="width: 500px;">
      <tr>
          <td>
              <table class="tb-acc-balance"> 
                  <tr>
                      <td>
                          Account balace:
                          <ol>
                          {% for key in balance %}
                            <li>{{balance[key]}} {{key}}</li>
                          {% endfor %}
                        </ol>
                      </td>
                  </tr>
              </table>
          </td>
          <td>
              {% if 'yes' in verified %}
              <table class="tb-verified" style="background-color: green;">
                  <tr>
                      <td style="background-color: green;">
                          Verified: {{verified}}
                      </td>
                  </tr>
              </table>
              {% else %}
              <table class="tb-verified" style="background-color: red;">
                <tr>
                    <td style="background-color: red;">
                        Verified: {{verified}}
                    </td>
                </tr>
            </table>
              {% endif%}
          </td>
      </tr>
      <tr>
          <td colspan="2">
              <table class="tb-acc-info" style="width: 100%;">
                  <tr>
                      <td>
                          Card number:
                          {{card['card_number']}}
                      </td>
                  </tr>
                  
                  <tr>
                      <td>
                          Full Name:
                          {{card['user_name']}}
                      </td>
                  </tr>
                  
                  <tr>
                      <td>
                          Valid Thru:
                          {{card['exp_date']}}
                      </td>
                  </tr>
                  
                  <tr>
                      <td>
                          PIN Code:
                          ****
                      </td>
                  </tr>
              </table>
          </td>
      </tr>
  </table>
  </div>

</body>

</html>

UI/Blueprints/bank/templates/card.html
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}"/>
  <meta name="author" content="SitePoint">
  <script type="text/javascript"
         src="{{ url_for('static', filename='js/jQuery.js') }}"></script>
  
</head>

<body>
    <ul style="width: 300px; line-height: 180%;" class="hornav-ul" >
        <li style="background-color: orange; height: 47px; width: 100%; float: left;" class="hornav-li"><img style="display: block; height: 50px; width: 50px; margin-bottom: 10px; margin-left: auto; margin-right: auto;" src="{{url_for('static', filename = 'images/shiba2.png')}}"/></li>
        <li style="width: 100%;" class="hornav-li-text"><a class="hornav-a" href="{{ url_for('bank.dashboard') }}">Dashboard</a></li>
        <li style="width: 100%;" class="hornav-li-text"><a class="hornav-a" href="{{ url_for('bank.transactions') }}">Transactions</a></li>
        <li style="width: 100%;" class="hornav-li-text active"><a class="hornav-a" href="{{ url_for('bank.card') }}">Credit card</a></li>
        <li style="width: 100%;" class="hornav-li-text"><a class="hornav-a" href="{{ url_for('bank.transfer') }}">Transfer money</a></li>
        <li style="width: 100%;" class="hornav-li-text"><a class="hornav-a" href="{{ url_for('bank.exchange') }}">Exchange currency</a></li>
      </ul>
      <ul class="topnav-ul">
        <li class="topnav-li"><a class="topnav-a" href="{{ url_for('main.logOut') }}">Log out</a></li>
        <li class="topnav-li"><a class="topnav-a" href="{{ url_for('main.profile') }}">Profile</a></li>
      </ul>
      <div style="position: absolute; top: 50px; left: 270px;">
        <table style="border: none; padding: 0; margin: 0; width: fit-content;">
            <tr>
                <td>
                    <form>
                        <table>
                            <tr>
                                <td>
                                    Verify card
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <input type="text" name="cardNum" id="cardNum" class="form-control" placeholder="Card Number (xxxx xxxx xxxx xxxx)" required autofocus>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <input type="text" name="userName" id="userName" class="form-control" placeholder="Full Name" required >
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <input type="number" name="pinCode" id="pinCode" class="form-control" placeholder="Pin Code" required >
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <input type="text" name="expDate" id="expDate" class="form-control" placeholder="Expiration Date (06/25)" required >
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <button id="btnInsertCard" class="login-button button" type="button">Verify</button>
                                </td>
                            </tr>
                        </table>
                    </form>
                </td>
                <td style="vertical-align: top; padding-left: 15px;">
                    <form>
                        <table>
                            <tr>
                                <td>
                                    Add funds
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <input type="number" name="amount" id="amount" class="form-control" placeholder="Amount" required >
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <select name="currency" id="currency" class="form-control" style="width: 415px;">
                                        <option>USD</option>
                                        {%for item in curr%}
                                        <option>{{item}}</option>
                                        {%endfor%}
                                    </select>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <button id="btnAddFunds" class="login-button button" type="button">Add funds</button>
                                </td>
                            </tr>
                        </table>
                    </form>
                </td>
            </tr>
        </table>
</div>


    <!-- The Modal -->
    <div id="myModal" class="modal">

      <!-- Modal content -->
      <div class="modal-content">
        <span class="close">&times;</span>
        <p id="modalTxt"></p>
      </div>

    </div>

    <script>
        // Get the modal
        var modal = document.getElementById("myModal");
    
        // Get the <span> element that closes the modal
        var span = document.getElementsByClassName("close")[0];
        
        let ele = document.getElementById('modalTxt');
        // When the user clicks on <span> (x), close the modal
        span.onclick = function() {
          modal.style.display = "none";
        }
    
        // When the user clicks anywhere outside of the modal, close it
        window.onclick = function(event) {
          if (event.target == modal) {
            modal.style.display = "none";
          }
        }
        $(function() {
          
        $('#btnInsertCard').click(function() {
     
            $.ajax({
                url: '/verifyOACC',
                data: $('form').serialize(),
                type: 'POST',
                success: function(response) {
                    modal.style.display = "block";
                    ele.innerHTML=response;
                    console.log(response);
                },
                error: function(error) {
                    console.log(error);
                }
            });
        });
    });
    $(function() {
          
          $('#btnAddFunds').click(function() {
       
              $.ajax({
                  url: '/addFunds',
                  data: $('form').serialize(),
                  type: 'POST',
                  success: function(response) {
                      modal.style.display = "block";
                      ele.innerHTML=response;
                      console.log(response);
                  },
                  error: function(error) {
                      console.log(error);
                  }
              });
          });
      });
      </script>
    
</body>

</html>

UI/Blueprints/bank/templates/data.html
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}"/>
  <meta name="author" content="SitePoint">
</head>

<body>

    
    
</body>

</html>

UI/Blueprints/bank/templates/exchange.html
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script type="text/javascript"
         src="{{ url_for('static', filename='js/jQuery.js') }}"></script>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}"/>
  <meta name="author" content="SitePoint">
</head>

<body>
    <ul style="width: 300px; line-height: 180%;" class="hornav-ul" >
        <li style="background-color: orange; height: 47px; width: 100%; float: left;" class="hornav-li"><img style="display: block; height: 50px; width: 50px; margin-bottom: 10px; margin-left: auto; margin-right: auto;" src="{{url_for('static', filename = 'images/shiba2.png')}}"/></li>
        <li style="width: 100%;" class="hornav-li-text"><a class="hornav-a"  href="{{ url_for('bank.dashboard') }}">Dashboard</a></li>
        <li style="width: 100%;" class="hornav-li-text"><a class="hornav-a" href="{{ url_for('bank.transactions') }}">Transactions</a></li>
        <li style="width: 100%;" class="hornav-li-text"><a class="hornav-a" href="{{ url_for('bank.card') }}">Credit card</a></li>
        <li style="width: 100%;" class="hornav-li-text"><a class="hornav-a" href="{{ url_for('bank.transfer') }}">Transfer money</a></li>
        <li style="width: 100%;" class="hornav-li-text active"><a class="hornav-a">Exchange currency</a></li>
    </ul>
    
    <ul class="topnav-ul">
        <li class="topnav-li"><a class="topnav-a" href="{{ url_for('main.logOut') }}">Log out</a></li>
        <li class="topnav-li"><a class="topnav-a" href="{{ url_for('main.profile') }}">Profile</a></li>
    </ul>
    <div style="position: absolute; top: 50px; left: 270px;">
        <form>
          <table>
            <tr>
                <td>
                    Exchange money
                </td>
            </tr>
            <tr>
                <td>
                  <input type="number" name="amount" id="amount" class="form-control" placeholder="Amount" required >
                </td>
            </tr>
            <tr>
                <td>
                  <select name="currencyFrom" id="currencyFrom" class="form-control" style="width: 415px;">
                    <option selected>From currency</option>
                    {%for item in _from%}
                    <option>{{item|replace('[\'','')|replace('\']','')}}</option>
                    {%endfor%}
                </select>
                </td>
            </tr>
            <tr>
                <td>
                  <select name="currencyTo" id="currencyTo" class="form-control" style="width: 415px;">
                    <option selected>To currency</option>
                    <option>USD</option>
                    {%for item in _to%}
                    <option>{{item}}</option>
                    {%endfor%}
                </select>
                </td>
            </tr>
            <tr>
                <td>
                  <button id="btnExchange" class="login-button button" type="button">Exchange</button>
                </td>
            </tr>
        </table>
        </form>
    </div> 

    <!-- The Modal -->
    <div id="myModal" class="modal">

      <!-- Modal content -->
      <div class="modal-content">
        <span class="close">&times;</span>
        <p id="modalTxt"></p>
      </div>

    </div>

  <script>
    // Get the modal
    var modal = document.getElementById("myModal");

    // Get the <span> element that closes the modal
    var span = document.getElementsByClassName("close")[0];
    
    let ele = document.getElementById('modalTxt');
    // When the user clicks on <span> (x), close the modal
    span.onclick = function() {
      modal.style.display = "none";
    }

    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function(event) {
      if (event.target == modal) {
        modal.style.display = "none";
      }
    }
    $(function() {
      
    $('#btnExchange').click(function() {
 
        $.ajax({
            url: '/exchangeInitiate',
            data: $('form').serialize(),
            type: 'POST',
            success: function(response) {
                modal.style.display = "block";
                ele.innerHTML=response;
                console.log(response);
            },
            error: function(error) {
                console.log(error);
            }
        });
    });
});
  </script>
</body>

</html>

UI/Blueprints/bank/templates/transactions.html
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}"/>
  <meta name="author" content="SitePoint">
  <script type="text/javascript"
         src="{{ url_for('static', filename='js/jQuery.js') }}"></script>
  
  <style>
    th{ text-align: left;}
    th:hover{
      cursor:pointer;
        }
    td{text-align: left;}

    

  </style>

</head>

<body>
    <ul style="width: 300px; line-height: 180%;" class="hornav-ul" >
        <li style="background-color: orange; height: 47px; width: 100%; float: left;" class="hornav-li"><img style="display: block; height: 50px; width: 50px; margin-bottom: 10px; margin-left: auto; margin-right: auto;" src="{{url_for('static', filename = 'images/shiba2.png')}}"/></li>
        <li style="width: 100%;" class="hornav-li-text"><a class="hornav-a" href="{{ url_for('bank.dashboard') }}">Dashboard</a></li>
        <li style="width: 100%;" class="hornav-li-text active"><a class="hornav-a" href="{{ url_for('bank.transactions') }}">Transactions</a></li>
        <li style="width: 100%;" class="hornav-li-text"><a class="hornav-a" href="{{ url_for('bank.card') }}">Credit card</a></li>
        <li style="width: 100%;" class="hornav-li-text"><a class="hornav-a" href="{{ url_for('bank.transfer') }}">Transfer money</a></li>
        <li style="width: 100%;" class="hornav-li-text"><a class="hornav-a" href="{{ url_for('bank.exchange') }}">Exchange currency</a></li>
      </ul>
      <ul class="topnav-ul">
        <li class="topnav-li"><a class="topnav-a" href="{{ url_for('main.logOut') }}">Log out</a></li>
        <li class="topnav-li"><a class="topnav-a" href="{{ url_for('main.profile') }}">Profile</a></li>
      </ul>
<div style="position: absolute; top: 60px; left: 260px; width: 60%;">
    <table style="width:100%; border: none; margin: 0px; padding: 0px;">
      <tr>
        <td style="width: 70%;">
          <table id="Transactions" style="width: 100%;">
              <tr>
                  <th onclick="sortTable(0)">Receiver</th>
                  <th onclick="sortTable(1)">Amount</th>
                  <th onclick="sortTable(2)">Currency</th>
                  <th >Date Time</th>
              </tr>
              {%for item in data%}
              <tr>
                <td>
                  {{item[0]}}
                </td>
                <td>
                  {{item[1]}}
                </td>
                <td>
                  {{item[2]}}
                </td>
                <td>
                  {{item[3]}}
                </td>
              </tr>
              {%endfor%}
          </table>
        </td>
        <td>
          <table style="width: 100%;">
              <tr>
                <td colspan="2"><input class="filter" type="text" id="To" onkeyup="filterTo()" placeholder="Search for Receiver..."></td>
              </tr>
              <tr>
                <td colspan="2"><input class="filter" type="text" id="Curr" onkeyup="filterCurr()" placeholder="Search for Currency..."></td>
              </tr>
              <tr>
                <td><input class="filter" type="text" id="FromA" onkeyup="filterA()" placeholder="From"></td>
                <td><input class="filter" type="text" id="ToA" onkeyup="filterA()" placeholder="To"></td>
              </tr>
          </table>
        </td>
      </tr>
    </table>
</div>
    
</body>

<script>
  function sortTable(n) {
    var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
    table = document.getElementById("Transactions");
    switching = true;
    // Set the sorting direction to ascending:
    dir = "asc";
    /* Make a loop that will continue until
    no switching has been done: */
    while (switching) {
      // Start by saying: no switching is done:
      switching = false;
      rows = table.rows;
      /* Loop through all table rows (except the
      first, which contains table headers): */
      for (i = 1; i < (rows.length - 1); i++) {
        // Start by saying there should be no switching:
        shouldSwitch = false;
        /* Get the two elements you want to compare,
        one from current row and one from the next: */
        x = rows[i].getElementsByTagName("TD")[n];
        y = rows[i + 1].getElementsByTagName("TD")[n];
        /* Check if the two rows should switch place,
        based on the direction, asc or desc: */
        if (dir == "asc") {
          if(n==1)
          {
            if (Number(x.innerHTML) > Number(y.innerHTML)) {
              shouldSwitch = true;
              break;
            }
          }
          else{
          if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
            // If so, mark as a switch and break the loop:
            shouldSwitch = true;
            break;
          }
        }
        } else if (dir == "desc") {
          if(n==1)
          {
            if (Number(x.innerHTML) < Number(y.innerHTML)) {
              shouldSwitch = true;
              break;
            }
          } else{
          if (x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase()) {
            // If so, mark as a switch and break the loop:
            shouldSwitch = true;
            break;
          }
        }
        }
      }
      if (shouldSwitch) {
        /* If a switch has been marked, make the switch
        and mark that a switch has been done: */
        rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
        switching = true;
        // Each time a switch is done, increase this count by 1:
        switchcount ++;
      } else {
        /* If no switching has been done AND the direction is "asc",
        set the direction to "desc" and run the while loop again. */
        if (switchcount == 0 && dir == "asc") {
          dir = "desc";
          switching = true;
        }
      }
    }
  }

  function filterTo() {
    // Declare variables
    var input, filter, table, tr, td, i, txtValue;
    input = document.getElementById("To");
    filter = input.value.toUpperCase();
    table = document.getElementById("Transactions");
    tr = table.getElementsByTagName("tr");

    // Loop through all table rows, and hide those who don't match the search query
      for (i = 0; i < tr.length; i++) {
        td = tr[i].getElementsByTagName("td")[0];
        if (td) {
          txtValue = td.textContent || td.innerText;
          if (txtValue.toUpperCase().indexOf(filter) > -1) {
              tr[i].style.display = "";
          } else {
            tr[i].style.display = "none";
          }
        }
      }
  }

  function filterCurr() {
    // Declare variables
    var input, filter, table, tr, td, i, txtValue;
    input = document.getElementById("Curr");
    filter = input.value.toUpperCase();
    table = document.getElementById("Transactions");
    tr = table.getElementsByTagName("tr");
  
    // Loop through all table rows, and hide those who don't match the search query
    // Loop through all table rows, and hide those who don't match the search query
      for (i = 0; i < tr.length; i++) {
        td = tr[i].getElementsByTagName("td")[2];
        if (td) {
          txtValue = td.textContent || td.innerText;
          if (txtValue.toUpperCase().indexOf(filter) > -1) {
              tr[i].style.display = "";
          } else {
            tr[i].style.display = "none";
          }
        }
      }
    }

    function filterA() {
    // Declare variables
    var from,to, table, tr, td, i, txtValue;
    from = document.getElementById("FromA");
    to = document.getElementById("ToA");
    table = document.getElementById("Transactions");
    tr = table.getElementsByTagName("tr");
    // Loop through all table rows, and hide those who don't match the search query
    // Loop through all table rows, and hide those who don't match the search query
    if(from.value !="" && to.value!=""){
      for (i = 0; i < tr.length; i++) {
        td = tr[i].getElementsByTagName("td")[1];
        if (td) {
          txtValue = td.textContent || td.innerText;
          if (Number(txtValue)<=Number(to.value) && Number(txtValue)>=Number(from.value)) {
              tr[i].style.display = "";
          } else {
            tr[i].style.display = "none";
          }
        }
      }
    }
    else{
      for (i = 0; i < tr.length; i++) {
        td = tr[i].getElementsByTagName("td")[1];
        if (td) {
              tr[i].style.display = "";
        }
      }
    }
  }

  </script>


</html>